#!/usr/bin/env python

import sys
import bumblebee.config
import bumblebee.engine

def main():
    config = bumblebee.config.Config(sys.argv[1:])

    engine = bumblebee.engine.Engine(config)
    engine.load_modules()

    engine.run()

if __name__ == "__main__":
    main()

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
